# Site settings
title:          LittlevGL's Blog
description:    "News and Tutorials for Embedded GUI Enthusiasts: Release notes of LittlevGL, Tutorials, Poring guides, Development board and microcontroller test, ideas, tips and tricks and more."

# Site settings
cover: /assets/def_post_cover.png

# Author
author:
  name:         Gabor Kiss-Vamosi
  email:        kisvegabor@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
